name: Reuse yml
on: workflow_call
jobs:
  checkout-and-install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Start"

      - name: Log
        run: echo "End"
