name: Matrix Demo
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      max-parallel: 6
      # fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16, 18]
        include:
          - os: macos-latest
          - node: 12
        exclude:
          - os: windows-latest
          - node: 14
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
