name: Reuse yml
on:
  workflow_call:
    inputs:
      file-name:
        description: Name of json file
        default: package1.json
        required: false
        type: string
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Start"
      - name: Get code
        uses: actions/checkout@v3
      - name: Upload File
        uses: actions/upload-artifact@v3
        with:
          name: json-file
          path: package.json
          if-no-files-found: error
      - name: Log2
        run: echo "End"
